server:
#  port: ${random.int[10000,19999]}
  port: 9011

spring:
  application:
    name: service-curly-umbrella
  profiles:
    active: develop

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka
#  instance:
#    instanceId: ${spring.application.name}:${random.int}

# ┐фиб
---
spring:
  profiles: develop
  datasource:
    primary:
      name: develop
      url: jdbc:mysql://127.0.0.1:3306/demo0528?characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: root
    secondary:
      url: jdbc:mysql://127.0.0.1:3306/curly_umbrella?characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

connection:
  readOnly: false
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
  maximumPoolSize: 100
  minimumIdle: 1
  autoCommit: false
  connectionTestQuery: SELECT 1