server:
  port: 9011

spring:
  profiles:
    active: develop

# ┐фиб
---
spring:
  profiles: develop
  datasource:
    name: develop
    url: jdbc:mysql://127.0.0.1:3306/demo0528?characterEncoding=UTF-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
